# -*- coding: utf-8 -*-
"""SANBLAS_202609_007_Conversion_de_tipos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDxSD4GNXWiFZBCbfWaqKnFDNCmdsI2N

### Conseguir que los tipos de las columnas sean int64, str, datetime y float64
"""

import pandas as pd

datos = {
    "id": range(1, 21),
    "producto": [
        "Portátil", "Ratón", "Teclado", "Monitor", "Auriculares",
        "Webcam", "Impresora", "Tablet", "Smartphone", "Disco SSD",
        "Memoria USB", "Altavoces", "Micrófono", "Silla", "Mesa",
        "Router", "Cargador", "Cable HDMI", "Disco duro", "Hub USB"
    ],
    "fecha de adquisición": [
        "15-01-2025", "22-01-2025", "03-02-2025", "18-02-2025",
        "25-02-2025", "10-03-2025", "21-03-2025", "05-04-2025",
        "17-04-2025", "29-04-2025", "08-05-2025", "19-05-2025",
        "02-06-2025", "14-06-2025", "27-06-2025", "09-07-2025",
        "20-07-2025", "04-08-2025", "16-08-2025", "28-08-2025"
    ],
    "precio": [
        899.99, "24.50", 45.90, "199.99", 79.95,
        "59.90", 149.99, "329.50", 699.00, "89.99",
        12.50, "45.00", "Treinta", "249.90", 179.99,
        "65.50", 29.99, "15.95", 110.00, "32.90"
    ]
}

df = pd.DataFrame(datos)

df.info()

# Conviertiendo la fila producto a string
df['producto']=df['producto'].astype('string')
df.info()

# Cambiar la fecha de adquisición a datetime
df['fecha de adquisición'] = pd.to_datetime(
    df['fecha de adquisición'],
    format='%d-%m-%Y') # En esta ocasión el formato no es necesario
df.info()
df

# Convertir el precio a float
df['precio'] = pd.to_numeric(df['precio'], errors='coerce')
# df['precio'] = df['precio'].astype('float') # No es necesario
df.info()

# Nos cargamos el registro que tiene un valor nulo
df=df.dropna() # Elimina los registros que tienen algún valor nulo
df.info()