# -*- coding: utf-8 -*-
"""SANBLAS_202609_013_Histograma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOUyREF7FIH4xzR8X5OBdzKIcvnyfvkq
"""

import pandas as pd
import matplotlib.pyplot as plt

datos = {
    "Alumnos": [f"Alumno {i}" for i in range(1, 101)],
    "Edad": [
        18, 19, 20, 21, 22, 22, 23, 23, 24, 24,
        25, 25, 26, 26, 27, 27, 28, 28, 29, 29,
        30, 30, 31, 31, 32, 32, 33, 33, 34, 34,
        35, 35, 36, 36, 37, 37, 38, 38, 39, 39,
        40, 40, 40, 40, 41, 41, 41, 41, 42, 42,
        42, 42, 43, 43, 43, 43, 44, 44, 44, 44,
        45, 45, 45, 45, 46, 46, 46, 46, 47, 47,
        48, 48, 49, 49, 50, 50, 51, 51, 52, 52,
        53, 53, 54, 54, 55, 55, 56, 56, 57, 58,
        59, 60, 61, 62, 63, 64, 65, 66, 68, 70
    ]
}

df = pd.DataFrame(datos)

df

plt.hist(df['Edad'], bins=10)
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.title('Distribución de Edades de Alumnos')
plt.show()