# -*- coding: utf-8 -*-
"""SANBLAS_202609_006_INTRO_PANDAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150y9ra__1ltM1PA1lsHglNVY5hGK6Bcl
"""

import pandas as pd

df = pd.DataFrame({
        'producto': [
            'Monitor', 'Auriculares', 'Webcam', 'Impresora', 'Tablet',
            'Disco SSD', 'Memoria RAM', 'Altavoces', 'Cargador', 'Cable HDMI',
            'Router', 'Smartphone', 'Silla', 'Mesa', 'Micrófono',
            'Teclado', 'Mouse', 'Laptop', 'Monitor', 'Auriculares'
        ],
        'precio': [
            300, 60, 90, 180, 450,
            100, 70, 45, 30, 15,
            75, 800, 250, 180, 120,
            65, 20, 1400, 350, 85
        ],
        'stock': [
            10, 30, 15, 8, 12,
            25, 40, 18, 35, 50,
            14, 6, 7, 10, 9,
            22, 60, 3, 8, 25
        ]
    })

df.info()

# Mostrar los datos de una serie
productos = df['producto']
print(type(productos)) # Serie
print(productos)

# Convertir las celdas de 'producto' a str
df['producto'] = df['producto'].astype('string')
# Convertir las celdas de 'precio' a float
df['precio'] = df['precio'].astype('float')
productos = df['producto']
print(type(productos)) # Serie
df.info()