# -*- coding: utf-8 -*-
"""SANBLAS_202609_012_CALIFICACIONES_Limpieza y diagramas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXaip2KbExFuMPhP4A7Xx3N30DyTUDKl
"""

import pandas as pd
import matplotlib.pyplot as plt

URL = "http://fpaniaguapython.github.io/datos/alumnos_calificaciones_por_asignatura.csv"

df = pd.read_csv(URL, delimiter=',', encoding='utf-8')
display(df.info())
display(df.head())

# Convertimos las columnas no numéricas (Historia) a número
df['Historia'] = pd.to_numeric(df['Historia'], errors='coerce')
display(df.info())
display(df)

# Asignamos los Alumnos a los índices

# En un paso --> Mueve la columna Alumno al índice
df.set_index('Alumno', inplace=True)

# En dos pasos:
# 1. Copia la columna Alumno al índice
# df.set_index(df['Alumno'], inplace=True)
# 2. Elimino la columna Alumno
# df.drop('Alumno', axis=1, inplace=True)

df

# Asignamos la media a los valores faltantes
df = df.T.fillna(df.mean(axis=1)).T
display(df)

# Eliminamos los duplicados
df = df.drop_duplicates()
df

# Añadimos las columnas de media, máximo y mínimo por alumno
# df_limpio = df # Se modifica el original
df_limpio = df.copy() # Se crea una copia
df_limpio['Media'] = df_limpio.mean(axis=1).round(1)
df_limpio['Máximo'] = df_limpio.max(axis=1)
df_limpio['Mínimo'] = df_limpio.min(axis=1)
df

# Crear un diagrama de puntos con las notas de los alumnos

plt.figure(figsize=(10, 6))

plt.xticks(rotation=-90)
plt.title('Notas de los alumnos')
plt.xlabel('Alumnos')
plt.ylabel('Notas')

plt.scatter(df.index, df['Matemáticas'], label='Matemáticas')
plt.scatter(df.index, df['Lengua'], label='Lengua')
plt.scatter(df.index, df['Historia'], label='Historia')

plt.show()

# Crear un diagrama directamente desde Pandas

pd.plotting.scatter_matrix(df, figsize=(10, 10))
plt.show()