# -*- coding: utf-8 -*-
"""Visualizador diagramas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPhnTpHkA_K2nSrHf_6uRx8_uOqUKqqq

# Visualizador de diagramas sencillo (30/09/2026)

## Imports 🐈
"""

import matplotlib.pyplot as plt
import pandas as pd

"""## Constantes❤️"""

URL = 'http://fpaniaguapython.github.io/datos/datos_diagrama.csv'

"""## Funciones 👌"""

def create_line_diagram(x_data, y_data):
    plt.plot(x_data, y_data)
    plt.title('Ventas trimestrales')
    plt.xlabel('Trimestres')
    plt.ylabel('Billones €')
    plt.show()

def create_bar_diagram(x_data, y_data):
    #plt.bar(x=x_data, height=y_data)
    plt.bar(x_data, y_data)
    plt.title('Ventas trimestrales')
    plt.xlabel('Trimestres')
    plt.ylabel('Billones €')
    plt.show()

"""## Lectura del CSV"""

df = pd.read_csv(URL)
df

"""## Obtención de las Series"""

trimestres = df['Trimestre'] # trimestres es Serie
ventas = df['Facturacion'] # ventas es Serie
#print(trimestres) # Funciona en cualquier sitio
trimestres # Solo funciona al final del código

"""## Creación de diagramas"""

create_bar_diagram(trimestres, ventas)
create_line_diagram(trimestres, ventas)