# -*- coding: utf-8 -*-
"""SANBLAS_202609_017_Ejercicio_subplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiYOPEebjMP2uJgUW-kl4PY0qYjp-L4_
"""

import matplotlib.pyplot as plt
import pandas as pd

URL = 'https://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2-2026-09.csv'

print('Leyendo datos del servidor...')
df = pd.read_csv(URL, sep=';', thousands='.')
df.head()

# Configuramos el estilo:
plt.style.use('seaborn-v0_8')

# Creando la figura y los subplots
fig, ax = plt.subplots(2,2,figsize=(10,10))

# Asignando los subplot a variables
diagrama_barras = ax[0,0]
diagrama_lineas = ax[0,1]
diagrama_tartas = ax[1,0]
diagrama_boxplot = ax[1,1]

# Solicitud del mes
print('Meses disponibles:')
print(list(df.columns[1:]))
mes = ''
while mes not in list(df.columns[1:]):
  mes = input('Mes: ')
  if mes not in list(df.columns[1:]):
    print('Mes no encontrado')

# Diagrama de la celda 0,0 del subplot (barras)
diagrama_barras.bar(df.iloc[1:,0], df[mes][1:])
diagrama_barras.set_xticks(df.iloc[1:,0])
diagrama_barras.tick_params(axis='x', labelrotation=-90)

# Diagrama de la celda 0,1 del subplot (líneas)
diagrama_lineas.plot(df.iloc[1:,0], df[mes][1:], color='coral')
diagrama_lineas.set_xticks(df.iloc[1:,0])
diagrama_lineas.tick_params(axis='x', labelrotation=-90)

# # Diagrama de la celda 1,0 del subplot (tartas)
diagrama_tartas.pie(
    df[mes][1:],
    labels=df.iloc[1:,0],
    autopct='%1.1f%%',
    textprops={'fontsize': 7})
diagrama_tartas.set_title(mes)

# # Diagrama de la celda 1,1 del subplot (boxplot)
diagrama_boxplot.boxplot(df[mes][1:])
diagrama_boxplot.set_xticklabels([''])
diagrama_boxplot.set_title(mes)

plt.tight_layout() # Ajusta la distribución de los gráficos
plt.show()