# -*- coding: utf-8 -*-
"""SANBLAS_202609_011_PANDAS_BASICO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182kHnfZZHNhHj51pLylrRCVdxlypIo6q
"""

import pandas as pd

datos = {
    "Alumno": ["Ana", "Luis", "Marta", "Carlos", "Sofía"],
    "Matemáticas": [8, None, 4, 7, 10],
    "Lengua extranjera": [7, 8, 9, None, 9],
    "Inglés": [9, 7, 8, 8, 10],
    "Historia": [5, 9, 7, 8, 9],
    "Física": [8, 10, 10, 7, 8]
}

df = pd.DataFrame(datos)

display(df)
display(df.columns)
display(df.index)
display(df)

# Cambiamos los nombres de las columnas
df.columns = df.columns.str.lower().str.replace(' ','_')
display(df.head())

# Cambiar el índice por el nombre de los alumnos
#df.index = df['alumno']
df.set_index(df['alumno'], inplace=True)
display(df.head())

# Eliminar la columna alumno
df.drop('alumno', axis=1, inplace=True)

display(df.head())

#df.dropna(axis=1, inplace=True) # Nos cargamos la columna que tiene NaN
#df.dropna(axis=0, inplace=True) # Nos cargamos la columna que tiene NaN
#display(df.head())

# Rellenar los NaN con la media de cada alumno
# La T obtiene la matriz transpuesta (intercambia filas por columnas)
# --> Necesario para que pueda calcular la media sobre las filas originales
df = df.T.fillna(df.mean(axis=1)).T
display(df.head())