# -*- coding: utf-8 -*-
"""SANBLAS_202609_016_Ejercicio_subplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Biww0nfH_8x5hLf2Cx3kFGiqB2LAIuVu
"""

import matplotlib.pyplot as plt
import numpy as np

# 0 es el inicio
# 10 el final
# 100 el número de elementos
x = np.linspace(0, 10, 100)

# fig --> figura.
# ax --> contenedor de índices
fig, ax = plt.subplots(2,2)

# Opción 1
# ax[0,0].plot(x, np.sin(x))
# ax[0,0].set_title('Función seno')
# ax[0,0].set_xlabel('Eje x')
# ax[0,0].set_ylabel('Eje y')

# ax[0,1].plot(x, np.cos(x))
# ax[1,0].plot(x, np.tan(x))
# ax[1,1].plot(x, x)

# Opción 2
subplot_seno = ax[0,0]
subplot_seno.plot(x, np.sin(x))
subplot_seno.set_title('Función seno')
subplot_seno.set_xlabel('Eje x')
subplot_seno.set_ylabel('Eje y')

subplot_cos = ax[0,1]
subplot_cos.plot(x, np.cos(x))

subplot_tan = ax[1,0]
subplot_tan.plot(x, np.tan(x))

subplot_linea = ax[1,1]
subplot_linea.plot(x, x)


plt.tight_layout() # Ajusta la distribución de los gráficos
plt.show()

