# -*- coding: utf-8 -*-
"""SANBLAS_202609_014_Cajasybigotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILcif6XauBE8hNnYTxE0b5IzxuzfALVV
"""

import pandas as pd
import matplotlib.pyplot as plt

# Crear un DataFrame con los datos

datos = {
    "Alumno": [f"Alumno {i}" for i in range(1, 22)],
    "Altura": [
        1.52, 1.55, 1.57, 1.58, 1.60,
        1.61, 1.62, 1.63, 1.64, 1.65,
        1.66, 1.67, 1.68, 1.69, 1.70,
        1.54, 1.59, 1.65,
        2.10, 1.20, 1.70,
    ]
}

df = pd.DataFrame(datos)

print(df)

plt.boxplot(df['Altura'], orientation='horizontal')
plt.title("Altura")
plt.xlabel("Alumnos")
plt.ylabel("Altura")
plt.show()