# -*- coding: utf-8 -*-
"""SANBLAS_202909_002_Matriculaciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIYKZmYPIK1FxJT_xu-VW-Oq0ay5Jc20

# Introducción
Los datos están obtenidos de:
https://www.faconauto.com/estadisticas/matriculaciones-de-turismos/

Los datos se encuentran alojados en:
http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2-2026-09.csv
"""

import pandas as pd
import matplotlib.pyplot as plt

URL_CSV = 'http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2-2026-09.csv'

df = pd.read_csv(URL_CSV, sep=';', thousands='.', decimal=',', skiprows=0)

df

comunidades = df['comunidad'].iloc[1:]
ventas_abril = df['abr-26'].iloc[1:]

plt.xticks(rotation=-90)
#plt.bar(comunidades, ventas_abril)
plt.bar(x=comunidades, height=ventas_abril)

plt.show()

plt.barh(y=df.columns[1:], width=df.iloc[3][1:])
plt.title(df.iloc[3]['comunidad'])
plt.show()

plt.pie(x=ventas_abril, labels=comunidades)
plt.show()