# -*- coding: utf-8 -*-
"""SANBLAS_202609_018_COLAB_ipywidgets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oj-QneIEkmyN2MvaJCIUuj2E_88qZ-0p
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# Campos del formulario
nombre = widgets.Text(
    description="Nombre:",
    placeholder="Escribe tu nombre",
    style={"description_width": "initial"}
)

analisis = widgets.Dropdown(
    options=["Estadístico", "Gráfico", "Predictivo"],
    description="Tipo:",
    style={"description_width": "initial"}
)

ejecutar = widgets.Button(
    description="Ejecutar análisis",
    button_style="primary",
    icon="play"
)

salida = widgets.Output()

def al_ejecutar(b):
    with salida:
        clear_output()
        print(f"Nombre: {nombre.value}")
        print(f"Análisis seleccionado: {analisis.value}")

ejecutar.on_click(al_ejecutar)

display(widgets.VBox([
    widgets.HTML("<h2>Configuración del análisis</h2>"),
    nombre,
    analisis,
    ejecutar,
    salida
]))