# -*- coding: utf-8 -*-
"""SANBLAS_202609_015_Ejercicio_boxplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F23L3ENSO4JR76O6bvG_9PpXdCgyrE5F
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

URL='http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2-2026-09.csv'

datos = pd.read_csv(URL, sep=';', decimal=',', thousands='.')

datos

# Total de matriculaciones

#plt.boxplot(datos.loc[0][1:], orientation='horizontal')
plt.boxplot(datos.iloc[0,1:], orientation='horizontal')
plt.title("Total matriculaciones")
plt.show()

# Total de Madrid
nombre_comunidad = 'COMUNIDAD DE MADRID'
#plt.boxplot(datos.iloc[10,1:], orientation='horizontal')

plt.title("Total matriculaciones Madrid")
plt.show()

# Por meses

plt.boxplot(datos.iloc[1:,1:], orientation='horizontal')
plt.title("Total ventas")
plt.ylabel("CCAA")

plt.yticks(
    range(12), # Posiciones
    datos.columns[1:] # Valores
)

plt.show()

# Por comunidades

plt.boxplot(datos.T.iloc[1:,1:], orientation='horizontal')
plt.title("Total matriculaciones")
plt.ylabel("CCAA")

plt.yticks(
    range(1, len(datos.iloc[1:]) + 1), # Posiciones
    datos.iloc[1:, 0] # Valores
)

plt.show()

datos.head()

# Por comunidades excluyendo las que matriculan muchos

#UMBRAL_ACUMULADO = np.inf
UMBRAL_ACUMULADO = 100_000

resultado = datos[datos[datos.columns[1:]].sum(axis=1) < UMBRAL_ACUMULADO]

plt.boxplot(resultado.T.iloc[1:,1:], orientation='horizontal')

plt.title("Total matriculaciones")
plt.ylabel("CCAA")

plt.yticks(
    range(1, len(resultado)), # Posiciones
    resultado['comunidad'][1:] # Valores
)

plt.show()

# Ordenación

# Por columna
# datos.sort_values(by='comunidad', inplace=True)

# Ordenar por acumulados
# datos = datos.loc[datos.iloc[:, 1:].sum(axis=1).sort_values(ascending=False).index]

# Ordenar por acumulados en dos pasos
datos['acumulado'] = datos.iloc[:,1:].sum(axis=1)
datos = datos.sort_values(by='acumulado',  ascending=False).drop(columns=['acumulado'])

display(datos)