# -*- coding: utf-8 -*-
"""SANBLAS_202609_010_Elecciones-CAM-2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IG9i2kMN6Hkjjc37qfIGuB8FAAuY7hcL
"""



"""## Carga de datos"""

# Fuente de los datos:
# https://resultados2023.comunidad.madrid/es/

import pandas as pd
import matplotlib.pyplot as plt

URL = 'http://fpaniaguapython.github.io/datos/DatEscrut_Def_Auto_2023_Madrid_Municipios.csv'

try:
    # El archivo utiliza comas (,) como separador en lugar de punto y coma (;)
    df = pd.read_csv(URL, encoding='latin-1', sep=',', thousands='.', decimal=',')
    print("Cargado con éxito usando encoding 'latin-1' y separador de coma")
    display(df.head())
except Exception as e:
    print(f"Error al cargar: {e}")

"""## Selección de columnas"""

datos = pd.concat([df['Municipio'], df['Censo Total'], df.iloc[:,13:]], axis=1)
datos

"""## Creación de nueva columna con los % de votos sobre un partido"""

partido = input('Introduce el partido')
partido = partido.upper()

datos['%'+partido] = round((datos[partido]/datos['Censo Total'])*100)
datos

"""## Asignamos el nombre del municipio (convertido a mayúculas) como índice y eliminamos la columna correspondiente"""

datos.set_index(datos['Municipio'].str.upper(), inplace=True) # Asignar como índice la columna Municipio
datos.drop(columns=['Municipio'], inplace=True) # Eliminando la columna Municipio
display(datos)

"""## Eliminar la última fila"""

datos = datos.iloc[:-1]
datos.tail()

"""## Diagrama de barras del municipio seleccionado"""

municipio = input('Municipio:')
municipio = municipio.upper()
# Excluimos las columnas primera y última
plt.bar(x=datos.columns[1:-1], height=datos.loc[municipio][1:-1])
plt.xticks(rotation=-90)
plt.title(municipio)
plt.show()

"""## Diagrama de tartas del municipio seleccionado"""

# Excluimos las columnas primera y última
plt.pie(x=datos.loc[municipio][1:-1], labels=datos.columns[1:-1])
plt.title(municipio)
plt.show()

"""## Diagrama de barras de % de votos de un partido político en los distintos municipios"""

plt.figure(figsize=(10, 40))
plt.barh(y=datos.index, width=datos['%'+partido])
plt.title('% de votos de '+partido)
plt.show()