# -*- coding: utf-8 -*-
"""SANBLAS_202609_005_INTRO_ANALISIS_DATOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5cESv-_YfNSORYdtvIoAZnjXk6orTQS
"""

import pandas as pd

ventas = pd.DataFrame({
        'producto': [
            'Monitor', 'Auriculares', 'Webcam', 'Impresora', 'Tablet',
            'Disco SSD', 'Memoria RAM', 'Altavoces', 'Cargador', 'Cable HDMI',
            'Router', 'Smartphone', 'Silla', 'Mesa', 'Micrófono',
            'Teclado', 'Mouse', 'Laptop', 'Monitor', 'Auriculares'
        ],
        'precio': [
            300, 60, 90, 180, 450,
            100, 70, 45, 30, 15,
            75, 800, 250, 180, 120,
            65, 20, 1400, 350, 85
        ],
        'stock': [
            10, 30, 15, 8, 12,
            25, 40, 18, 35, 50,
            14, 6, 7, 10, 9,
            22, 60, 3, 8, 25
        ]
    })

"""### Mostrar las 5 primeras filas"""

ventas.head() # Si le pasamos un entero, muestra ese número de registros

"""### Mostrar las 5 últimas filas"""

ventas.tail() # Si le pasamos un entero, muestra ese número de registros

"""### Mostrar registros al azar"""

ventas.sample(3)

"""### Mostrar la información de la estructura del df

"""

ventas.info()

"""### Mostrar información del diseño del df"""

ventas.shape # Filas, Columnas

"""### Mostrar los tipos de datos"""

ventas.dtypes

"""### Mostrar estadísticas descriptivas básicas"""

ventas.describe()