# -*- coding: utf-8 -*-
"""SANBLAS_202609_04_DF_FROM_HTML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PZ90CYGJ0SInzB0SJR9IinmB7efQCLl
"""

import pandas as pd
import requests

url = "https://es.wikipedia.org/wiki/National_Basketball_Association#Palmar%C3%A9s"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/140.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)
response.raise_for_status()

df = pd.read_html(response.text)

df[3]