# -*- coding: utf-8 -*-
"""SANBLAS_202609_009_Elecciones-CAM-2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Qos85vLd2vRG3Gf-AKO3UGFfSt6s97K
"""

# Fuente de los datos:
# https://resultados2023.comunidad.madrid/es/

import pandas as pd
import matplotlib.pyplot as plt


URL = 'http://fpaniaguapython.github.io/datos/DatEscrut_Def_Auto_2023_Madrid_Municipios.csv'

try:
    # El archivo utiliza comas (,) como separador en lugar de punto y coma (;)
    df = pd.read_csv(URL, encoding='latin-1', sep=',', thousands='.', decimal=',')
    print("Cargado con éxito usando encoding 'latin-1' y separador de coma")
    display(df.head())
except Exception as e:
    print(f"Error al cargar: {e}")

df.tail()

# Eliminación de la última fila
df = df.iloc[:-1]
df.tail()

# Eliminación de la columna "Unnamed: 3"
# df_sin_columna = df.drop(columns=["Unnamed: 3"])
df.drop(columns=["Unnamed: 3"], inplace=True)
df.head()

# El 1 indica que se concatenan las columnas
votos = pd.concat([df.iloc[:,2],df.iloc[:,12:]], axis=1)
votos

# Asignar la columna de municipios a los índices de las filas
votos.set_index(votos['Municipio'].str.upper(), inplace=True)
votos.drop(columns=['Municipio'], inplace=True)
votos

municipio = input('Introduce el nombre de un municipio: ')
municipio = municipio.upper()
votos_alcorcon = votos.loc[municipio]
plt.pie(votos_alcorcon, labels=votos_alcorcon.index, autopct='%1.1f%%')
plt.title(f'Votos en el Municipio de {municipio}')