# -*- coding: utf-8 -*-
"""SANBLAS_202609_008_Tratamiento_datos_y_diagramas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGkVP56xXnErPEUkg3FGLkKLPW3u77xP
"""

import pandas as pd

datos = {
    "id": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20,
        21, 22, 23, 24, 25
    ],

    "titulo de la pelicula": [
        "El último viaje",
        "Sombras del pasado",
        "Misión Estelar",
        "La ciudad perdida",
        "Horizonte rojo",
        "El secreto del bosque",
        "Noche de tormenta",
        "Aventuras en Marte",
        "El reino olvidado",
        "Código desconocido",
        "La gran escapada",
        "Destino final",
        "Guardianes de la Tierra",
        "El misterio del lago",
        "Viaje al centro",
        "Operación Aurora",
        "Los últimos héroes",
        "Más allá del tiempo",
        "La isla perdida",
        "El despertar",
        "Crónicas del futuro",
        "El legado",
        "Bajo las estrellas",
        "La última misión",
        "El nuevo mundo"
    ],

    "fecha de estreno": [
        "01#15/2023",
        "02#20/2023",
        "03#10/2023",
        "04#05/2023",
        "05#18/2023",
        "06#22/2023",
        "07#14/2023",
        "08#30/2023",
        "09#12/2023",
        "10#27/2023",
        "11#05/2023",
        "12#18/2023",
        "01#25/2024",
        "02#14/2024",
        "03#29/2024",
        "04#10/2024",
        "05#24/2024",
        "06#15/2024",
        "07#28/2024",
        "08#09/2024",
        "09#21/2024",
        "10#31/2024",
        "11#16/2024",
        "13#45/2024",       # Fecha incorrecta
        "12#20/2027"        # Fecha futura
    ],

    "taquilla (€)": [
        1250000.50,
        875000.75,
        "dos millones",
        3500000.00,
        "quinientos mil",
        4250000.80,
        980000.25,
        "un millón doscientos mil",
        2750000.00,
        650000.50,
        "ochocientos mil",
        5100000.00,
        3250000.75,
        "tres millones",
        1450000.25,
        4900000.00,
        "veinte mil",
        2100000.50,
        3750000.00,
        "un millón",
        2850000.75,
        4500000.00,
        "seis millones",
        600000000.00,       # 100 veces mayor que 6.000.000
        3950000.50
    ]
}

df = pd.DataFrame(datos)

df.info()

# Convertir el título a string

df['titulo de la pelicula']=df['titulo de la pelicula'].astype('string')
df.info()

mascara = '%m#%d/%Y'
df['fecha de estreno'] = pd.to_datetime(
    df['fecha de estreno'],
    errors='coerce',
    format=mascara)
# df_copia = df.dropna()
df.dropna(inplace=True)
df.info()

# Conversión de la taquilla a numérico (float)
df['taquilla (€)'] = pd.to_numeric(df['taquilla (€)'], errors='coerce')
# Sustitución de los NaN de la taquilla por la media
df['taquilla (€)'].fillna(df['taquilla (€)'].mean(), inplace=True)
# Conversión de la taquilla a int
df['taquilla (€)'] = df['taquilla (€)'].astype('int')
print(df.head())
df.info()